package stateMachine;

public enum StateMachineType {
    ROAM, SCORE, COLLECT_FROM_ENERGY_SILO, COLLECT_GROUND_BALLS, DEPOSIT_RED_BALLS, AVOID_WALLS, STOPPED,
    LOOK_FOR_BALLS, SCORE_IN_REACTOR, SORT, WALL_FOLLOW;
}
